field: 138d0eae-ea95-4e6e-86c6-9e927e7e72e2
fieldLayouts:
  b77555fd-7d88-4ce5-8736-aa445c1ff2f0:
    tabs:
      -
        elements:
          -
            fieldUid: b5e240b8-7510-4f85-9c27-f77034980982
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48358b4d-d9df-4e57-a67e-ee2f38c129b0
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: be1c655e-7827-4296-9c27-3420d6081b0e
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d9d2060f-7b6a-411e-8fc1-0ad671e9df58
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  48358b4d-d9df-4e57-a67e-ee2f38c129b0:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Afbeelding
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:6576af27-2464-42a5-93ba-12b804de04f1' # Header
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:6576af27-2464-42a5-93ba-12b804de04f1' # Header
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:6576af27-2464-42a5-93ba-12b804de04f1' # Header
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b5e240b8-7510-4f85-9c27-f77034980982:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Titel
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be1c655e-7827-4296-9c27-3420d6081b0e:
    contentColumnType: string
    fieldGroup: null
    handle: linkedCategory
    instructions: 'Let op: dit moet een category van activiteiten zijn. Wanneer gekozen wordt voor een activiteit, zal deze niet getoond worden. '
    name: 'Gekoppelde category'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:a9f5d80c-3a46-4c6c-8060-9e91f1246dbb'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  d9d2060f-7b6a-411e-8fc1-0ad671e9df58:
    contentColumnType: string
    fieldGroup: null
    handle: usps
    instructions: ''
    name: 'Usp''s'
    searchable: true
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      limit: null
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: 'taggroup:8a953043-f1a0-4cd1-b83b-ff73d0458e0d'
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Tags
handle: category
name: 'Categorie item'
sortOrder: 1
