field: d16c24d1-abfe-4e08-b18c-45bcb368c93f # Inhoud
fieldLayouts:
  71893719-2b48-4d48-af58-3b94683a246a:
    tabs:
      -
        elements:
          -
            fieldUid: af1ecf9f-e8a5-4aac-9ba8-191015443a7c # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 34a70bbd-9aba-45a1-82f4-bcf7a1cc1272 # Blokken
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  34a70bbd-9aba-45a1-82f4-bcf7a1cc1272: # Blokken
    contentColumnType: string
    fieldGroup: null
    handle: blocks
    instructions: ''
    name: Blokken
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - be6d8db1-6e50-4334-987c-ab524c903c0f # Titel
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - f3ecab75-c1e2-4d45-933e-171a328e5a3b # Subtitel
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 38af146a-0d6b-417d-abe2-dcc73f0bb167 # Hoofdcontent
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 1fc21d5a-9daa-455b-8adb-f1f250beecb5 # Subcontent
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - c6bfc555-2539-4fb7-8c6b-1decfe5a7983 # CTA
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 3251a7c0-65ee-4e96-810f-564919de6cf6 # CTA - micro tekst
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_23_blocks}}'
      fieldLayout: matrix
      maxRows: '3'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Voeg blok toe'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  af1ecf9f-e8a5-4aac-9ba8-191015443a7c: # Tekst
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Tekst
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: ctaBlocks
name: 'CTA blokken'
sortOrder: 6
