field: d16c24d1-abfe-4e08-b18c-45bcb368c93f
fieldLayouts:
  fbb450b9-a2b5-4ba7-9b9c-3252fbbda6bf:
    tabs:
      -
        elements:
          -
            fieldUid: 6a956667-50c6-45d4-abb1-9585ab9cbdd9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3c84b104-72c4-48a0-844a-9106c2d67158
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3c84b104-72c4-48a0-844a-9106c2d67158:
    contentColumnType: boolean
    fieldGroup: null
    handle: openingHours
    instructions: 'Toon openingstijden tabel'
    name: 'Toon tabel'
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  6a956667-50c6-45d4-abb1-9585ab9cbdd9:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Tekst
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: openingHours
name: Openingstijden
sortOrder: 13
