field: d16c24d1-abfe-4e08-b18c-45bcb368c93f
fieldLayouts:
  8497de2c-5898-4358-a377-484e568723eb:
    tabs:
      -
        elements:
          -
            fieldUid: 8860e9d9-93a8-4ea0-aed8-b316eb1320b9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1af7a26b-524f-4c88-a76d-4c33f3e5b935
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 739ca29a-ea7d-47e0-a09d-421e1d26c982
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1af7a26b-524f-4c88-a76d-4c33f3e5b935:
    contentColumnType: string
    fieldGroup: null
    handle: partners
    instructions: ''
    name: Partners
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  739ca29a-ea7d-47e0-a09d-421e1d26c982:
    contentColumnType: boolean
    fieldGroup: null
    handle: partnersShowAll
    instructions: 'Toont alle partners, ongeacht wat in het vorige veld is ingevuld'
    name: 'Toon alle partners'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  8860e9d9-93a8-4ea0-aed8-b316eb1320b9:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Tekst
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: partners
name: Partners
sortOrder: 16
