field: d16c24d1-abfe-4e08-b18c-45bcb368c93f
fieldLayouts:
  d20b0b7d-09ad-40f6-9fe7-43c9dd07f433:
    tabs:
      -
        elements:
          -
            fieldUid: 60ba4af7-9102-49ee-bdde-8f14a6e03c71
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ab043be5-9526-4503-b7f2-d7d8e3c5bc7d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c8662e4e-330e-469b-9334-72665e8bd5a4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  60ba4af7-9102-49ee-bdde-8f14a6e03c71:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Tekst
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ab043be5-9526-4503-b7f2-d7d8e3c5bc7d:
    contentColumnType: boolean
    fieldGroup: null
    handle: showServices
    instructions: ''
    name: 'Toon voorzieningen'
    searchable: true
    settings:
      default: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  c8662e4e-330e-469b-9334-72665e8bd5a4:
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: ''
    name: CTA
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        4: entry
        6: custom
        7: email
        8: tel
        9: url
      autoNoReferrer: '1'
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - solspaceCalendar-event
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
handle: services
name: Voorzieningen
sortOrder: 15
