field: 138d0eae-ea95-4e6e-86c6-9e927e7e72e2
fieldLayouts:
  0edcb8d7-41b1-426a-b8ae-1713fa3beb7e:
    tabs:
      -
        elements:
          -
            fieldUid: 58294a97-ce53-40e4-b1c5-c022bd118f7c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 99dfec15-fa69-4b28-ab86-c9d47dbf7784
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a65105e6-0e11-4b38-9eaf-05498b84ad6f
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a5ca32cc-3989-44d0-b160-571b015899f9
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  58294a97-ce53-40e4-b1c5-c022bd118f7c:
    contentColumnType: text
    fieldGroup: null
    handle: serviceTitle
    instructions: ''
    name: Titel
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  99dfec15-fa69-4b28-ab86-c9d47dbf7784:
    contentColumnType: string
    fieldGroup: null
    handle: serviceImage
    instructions: ''
    name: Afbeelding
    searchable: true
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:6576af27-2464-42a5-93ba-12b804de04f1'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:4176b138-ab46-48c2-ba93-8f81e9d3c0df'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a5ca32cc-3989-44d0-b160-571b015899f9:
    contentColumnType: string
    fieldGroup: null
    handle: serviceUsps
    instructions: ''
    name: 'Usp''s'
    searchable: true
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      limit: null
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: 'taggroup:8a953043-f1a0-4cd1-b83b-ff73d0458e0d'
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Tags
  a65105e6-0e11-4b38-9eaf-05498b84ad6f:
    contentColumnType: string
    fieldGroup: null
    handle: serviceColor
    instructions: ''
    name: Kleur
    searchable: true
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Teal
            -
              - value
              - teal
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Geel
            -
              - value
              - yellow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Rood
            -
              - value
              - red
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
handle: service
name: Categorie
sortOrder: 1
