field: d16c24d1-abfe-4e08-b18c-45bcb368c93f
fieldLayouts:
  6dc945e3-81df-4ca9-b312-d228156d6af8:
    tabs:
      -
        fields:
          670a5a79-e711-4d6c-83f9-e57598d510fc:
            required: true
            sortOrder: 2
          b418fe90-7e19-4457-a1b0-4a975cdc9f4d:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  670a5a79-e711-4d6c-83f9-e57598d510fc:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Afbeeldingen
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:6576af27-2464-42a5-93ba-12b804de04f1'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:6576af27-2464-42a5-93ba-12b804de04f1'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b418fe90-7e19-4457-a1b0-4a975cdc9f4d:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Tekst
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: slider
name: Slider
sortOrder: 9
