field: d16c24d1-abfe-4e08-b18c-45bcb368c93f # Inhoud
fieldLayouts:
  5d51dcd5-2e8c-4b52-96f3-a2bd01ea86ee:
    tabs:
      -
        elements:
          -
            fieldUid: 49d35a69-4421-4bae-bac8-3397f6d650a5 # Tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e4e34eb6-61ee-45c2-87d2-e5844de66f42 # Kolom titels
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e1426067-79a5-4525-903a-b880012b9699 # Tabel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  49d35a69-4421-4bae-bac8-3397f6d650a5: # Tekst
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Tekst
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e4e34eb6-61ee-45c2-87d2-e5844de66f42: # Kolom titels
    contentColumnType: boolean
    fieldGroup: null
    handle: columnTitle
    instructions: 'Moet de eerste rij van de tabel als hoofdkolom dienen'
    name: 'Kolom titels'
    searchable: true
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  e1426067-79a5-4525-903a-b880012b9699: # Tabel
    contentColumnType: text
    fieldGroup: null
    handle: table
    instructions: "Niet alle kolommen dienen ingevuld te worden.\r\nMocht het een tabel zijn met bijvoorbeeld 3 kolommen, dan dienen alleen de eerste drie kolommen ingevuld te worden."
    name: Tabel
    searchable: true
    settings:
      addRowLabel: 'Voeg een rij toe'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Kolom 1'
                -
                  - handle
                  - column1
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - 'Kolom 2'
                -
                  - handle
                  - column2
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'Kolom 3'
                -
                  - handle
                  - column3
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - 'Kolom 4'
                -
                  - handle
                  - column4
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
            -
              - col4
              - ''
      maxRows: ''
      minRows: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: table
name: Tabel
sortOrder: 12
