fieldLayouts:
  8cb9ecdb-67f2-45e2-bc36-4b3081a37d67:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 5e04aee6-fa48-49e3-b86f-882b8ea36b9c
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3a0f8407-4263-4449-9996-e53070168b78
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: dcba1bec-77c1-4e56-98bb-7b73ff2a87fc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 39ac3118-752f-4170-85e7-bef7a88b14ff
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d16c24d1-abfe-4e08-b18c-45bcb368c93f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 682ecbc3-2252-4e4d-ac77-decc7ed47b7b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 34fc4e87-8df5-481d-bfad-75b58bf17d76
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Contact blok'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 8d69ebf3-f317-4814-846f-b7f4fe0494b1
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 3
handle: activitiesOverview
hasTitleField: false
name: 'Activiteiten - Overzicht'
section: 6c837388-83a1-497d-b47b-ed3dbdff5dac
sortOrder: 1
titleFormat: '{commonTitle}'
