fieldLayouts:
  961d16f4-812f-4ed5-b413-2c9e1dcba803:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 3a0f8407-4263-4449-9996-e53070168b78 # Header afbeelding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d16c24d1-abfe-4e08-b18c-45bcb368c93f # Inhoud
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 682ecbc3-2252-4e4d-ac77-decc7ed47b7b # Contact blok - Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 34fc4e87-8df5-481d-bfad-75b58bf17d76 # Contact blok - Toon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Contact blok'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 8d69ebf3-f317-4814-846f-b7f4fe0494b1 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: contentpage
hasTitleField: true
name: Contentpagina
section: b541f192-3512-4391-af9d-aaad78edfeb5 # Contentpagina
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
