fieldLayouts:
  961d16f4-812f-4ed5-b413-2c9e1dcba803:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Titel
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 3a0f8407-4263-4449-9996-e53070168b78
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d16c24d1-abfe-4e08-b18c-45bcb368c93f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Inhoud
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 682ecbc3-2252-4e4d-ac77-decc7ed47b7b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 34fc4e87-8df5-481d-bfad-75b58bf17d76
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Contact blok'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 8d69ebf3-f317-4814-846f-b7f4fe0494b1
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 3
handle: contentpage
hasTitleField: true
name: Contentpagina
section: b541f192-3512-4391-af9d-aaad78edfeb5
sortOrder: 1
titleFormat: ''
