fieldLayouts:
  f70221d6-d905-48a4-93d1-43232c388a21:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Titel
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 5e04aee6-fa48-49e3-b86f-882b8ea36b9c
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 526e0682-d673-4a69-abfc-75054fd47251
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3a0f8407-4263-4449-9996-e53070168b78
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d16c24d1-abfe-4e08-b18c-45bcb368c93f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 682ecbc3-2252-4e4d-ac77-decc7ed47b7b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 34fc4e87-8df5-481d-bfad-75b58bf17d76
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Contact blok'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 8d69ebf3-f317-4814-846f-b7f4fe0494b1
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 3
handle: facilities
hasTitleField: false
name: Faciliteiten
section: 89816d2a-ba5d-4fdf-ab8c-36b20e10af44
sortOrder: 1
titleFormat: '{commonTitle}'
