fieldLayouts:
  9f531ed5-f03f-4274-ba10-147b799bff0d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 88787612-5b03-4a0b-82b6-2113e3a05dc4
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0e7ee76e-d485-4b6a-9a37-debfe93a5d4c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: FAQ
        sortOrder: 1
handle: faq
hasTitleField: false
name: FAQ
section: 138fd91c-e286-44c3-823f-e2380e31883c
sortOrder: 1
titleFormat: '{question}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
