fieldLayouts:
  b5a10ae0-286a-46b9-b1de-663fae6375fb:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Titel
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 6411c6f0-8af3-4a83-8ba6-7a5778adb9e9
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ef04d81b-a107-4503-96ba-170438728574
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: services
hasTitleField: true
name: Voorzieningen
section: 4e86169f-ead1-452f-ba4c-37205c2e86dc
sortOrder: 1
titleFormat: ''
