allowRepeatingEvents: true
color: '#F3E966'
description: 'Rooster van wedstrijdbad'
descriptionFieldHandle: '0'
fieldLayout:
  tabs:
    -
      elements:
        -
          fieldUid: 25aa4096-013f-4913-8ad6-8bb1dd1c2889
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 100
      name: Gegevens
      sortOrder: 1
  uid: 4c12e610-7e6b-46aa-b115-37102ebdd7f2
handle: competitionPool
hasTitleField: true
icsHash: null
icsTimezone: floating
locationFieldHandle: '0'
name: Wedstrijdbad
siteSettings:
  0fa03155-1ea7-4e70-9dd7-75ad25fb8cb0:
    enabledByDefault: true
    hasUrls: false
    siteId: 521def3a-78c9-4e7b-8cb5-40b18c2c0705
    template: null
    uriFormat: null
titleFormat: ''
titleLabel: Title
