fieldLayouts:
  6f7223b8-8f82-4fcd-a198-cdd10d86315e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: header
hasUrls: true
name: Header
settings:
  path: '@mediaPath/header'
sortOrder: 1
type: craft\volumes\Local
url: '@mediaUrl/header'
