fieldLayouts:
  fa5bc59e-cb60-44b1-acc4-6f89699c696d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: partners
hasUrls: true
name: Partners
settings:
  path: '@mediaPath/partners'
sortOrder: 4
type: craft\volumes\Local
url: '@mediaUrl/partners'
