fieldLayouts:
  f28a6a73-ca4b-44a7-81f4-f680c4a6fa1a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: team
hasUrls: true
name: Team
settings:
  path: '@mediaPath/team'
sortOrder: 5
type: craft\volumes\Local
url: '@mediaUrl/team'
