contentColumnType: text
fieldGroup: 7b0ef5c0-4291-4913-932b-32945e1c974f # Activiteiten
handle: activitiesOverviewTitle
instructions: ''
name: 'Categorie - Overzichtstitel'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
