contentColumnType: integer
fieldGroup: df78e26d-9aa7-49a4-bd8a-75980ddba39d
handle: calendar2
instructions: ''
name: 'Kalender - 2'
searchable: true
translationKeyFormat: null
translationMethod: none
type: Solspace\Calendar\FieldTypes\CalendarFieldType
