contentColumnType: text
fieldGroup: df78e26d-9aa7-49a4-bd8a-75980ddba39d
handle: calendarTitle
instructions: ''
name: 'Kalender - Titel'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
