contentColumnType: text
fieldGroup: df78e26d-9aa7-49a4-bd8a-75980ddba39d
handle: calendarCta
instructions: ''
name: 'Kalender - CTA'
searchable: true
settings:
  allowCustomText: '1'
  allowTarget: '1'
  allowedLinkNames:
    1: asset
    4: entry
    6: custom
    7: email
    8: tel
    9: url
  autoNoReferrer: '1'
  defaultLinkName: custom
  defaultText: 'Bekijk alle activiteiten'
  enableAriaLabel: ''
  enableTitle: ''
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - category
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - user
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - site
        -
          __assoc__:
            -
              - sites
              - '*'
      -
        - custom
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - email
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - tel
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - url
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - solspaceCalendar-event
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
translationKeyFormat: null
translationMethod: none
type: typedlinkfield\fields\LinkField
