contentColumnType: text
fieldGroup: ae9ca910-6694-4017-a02d-bbea31a82b3a
handle: facilitiesOverviewTitle
instructions: ''
name: Overzichtstitel
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
