contentColumnType: string
fieldGroup: f0c3735f-1b6e-456c-9608-4cfe64ddcd90
handle: newsItems
instructions: ''
name: 'Nieuws - Items'
searchable: true
settings:
  allowSelfRelations: ''
  limit: '3'
  localizeRelations: false
  selectionLabel: ''
  source: null
  sources:
    - 'section:b8b9d7b2-37ec-4448-9ebb-6e32ee552f42'
  targetSiteId: null
  validateRelatedElements: ''
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
