contentColumnType: string(255)
fieldGroup: 3218d4a4-32d4-4586-bf1e-4250b36e0bc1
handle: partnerUrl
instructions: 'Url van de website van de partner'
name: 'Partner - Url'
searchable: false
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
