contentColumnType: string
fieldGroup: f0c3735f-1b6e-456c-9608-4cfe64ddcd90 # Home
handle: preview
instructions: ''
name: Preview
searchable: true
settings:
  contentTable: '{{%matrixcontent_preview}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
