contentColumnType: text
fieldGroup: cdcb72f5-a94d-46ed-ab22-67dcb5fff45f
handle: pricesRest
instructions: ''
name: 'Tarieven - Overige prijzen'
searchable: true
settings:
  addRowLabel: 'Voeg een rij toe'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Overige activiteiten'
            -
              - handle
              - activities
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Per keer'
            -
              - handle
              - price
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Strippenkaart
            -
              - handle
              - priceCard
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
