contentColumnType: string
fieldGroup: df78e26d-9aa7-49a4-bd8a-75980ddba39d
handle: prices
instructions: ''
name: 'Tarieven - Blokken'
searchable: true
settings:
  contentTable: '{{%matrixcontent_prices}}'
  maxBlocks: '3'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
