contentColumnType: string
fieldGroup: cdcb72f5-a94d-46ed-ab22-67dcb5fff45f # Global
handle: pricesTickets
instructions: ''
name: 'Tarieven - Tickets'
searchable: true
settings:
  contentTable: '{{%matrixcontent_pricestickets}}'
  maxBlocks: '3'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
