field: 34a70bbd-9aba-45a1-82f4-bcf7a1cc1272 # Blokken
fieldLayouts:
  0c6e60b9-5875-41c9-bb4a-e98af5abbe49:
    tabs:
      -
        elements:
          -
            fieldUid: be6d8db1-6e50-4334-987c-ab524c903c0f # Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f3ecab75-c1e2-4d45-933e-171a328e5a3b # Subtitel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 38af146a-0d6b-417d-abe2-dcc73f0bb167 # Hoofdcontent
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1fc21d5a-9daa-455b-8adb-f1f250beecb5 # Subcontent
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c6bfc555-2539-4fb7-8c6b-1decfe5a7983 # CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3251a7c0-65ee-4e96-810f-564919de6cf6 # CTA - micro tekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1fc21d5a-9daa-455b-8adb-f1f250beecb5: # Subcontent
    contentColumnType: text
    fieldGroup: null
    handle: subContent
    instructions: ''
    name: Subcontent
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: List.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  38af146a-0d6b-417d-abe2-dcc73f0bb167: # Hoofdcontent
    contentColumnType: string
    fieldGroup: null
    handle: mainContent
    instructions: ''
    name: Hoofdcontent
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_maincontent}}'
      maxBlocks: '1'
      minBlocks: '1'
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  3251a7c0-65ee-4e96-810f-564919de6cf6: # CTA - micro tekst
    contentColumnType: text
    fieldGroup: null
    handle: ctaMicro
    instructions: 'Micro tekst onder de knop wordt alleen getoond wanneer CTA is ingevuld'
    name: 'CTA - micro tekst'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be6d8db1-6e50-4334-987c-ab524c903c0f: # Titel
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Titel
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c6bfc555-2539-4fb7-8c6b-1decfe5a7983: # CTA
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: ''
    name: CTA
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        1: asset
        4: entry
        7: email
        8: tel
        9: url
      autoNoReferrer: ''
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: '1'
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - solspaceCalendar-event
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  f3ecab75-c1e2-4d45-933e-171a328e5a3b: # Subtitel
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: ''
    name: Subtitel
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
