fieldLayouts:
  da5a2b56-e6b9-4bf8-bc9c-7b4cd7dd7448:
    tabs:
      -
        elements:
          -
            fieldUid: 4e9173fd-9444-4cad-8f4e-532eaa7ce1f7 # Contact - Straat & huisnummer
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b660e663-9d28-4b7f-bf32-2ff921bcc3c1 # Contact - Plaats
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 990e683c-9217-48b2-9d27-0208bc3339fd # Contact - Postcode
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7ffa6f74-ddee-45e0-bb12-68def0320384 # Contact - Telefoonnummer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4a1103f1-acec-4eae-9259-d9ef1e9a05fb # Contact - Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contact
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4ca82977-e9ee-4f4b-87fd-5a879b9b4707 # Contact blok - Titel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bc6ad484-fb43-4e27-ab54-1b0eab2c92b8 # Contact blok - Telefoonnummer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 799b722b-ef73-43c7-81e8-60712f17e3d5 # Contact blok - CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contactblok
        sortOrder: 2
handle: contact
name: Contact
sortOrder: 1
