fieldLayouts:
  2ced5afb-e715-43b6-9eae-03950c6ecc0d:
    tabs:
      -
        elements:
          -
            fieldUid: a460ba7f-4818-4183-b551-28d816e087db
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Tickets
        sortOrder: 1
handle: prices
name: Tarieven
