fieldLayouts:
  808033d7-7037-46f1-a757-7411b0f8de27:
    tabs:
      -
        elements:
          -
            fieldUid: 56974294-62e1-4d99-b0b7-d2ce74ff2dee
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ca1458cf-ba61-4ef9-84aa-2a09d4886e98
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8cf5091d-c55c-4348-a57f-b38c56bc0aa0
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Social
        sortOrder: 1
handle: social
name: Social
