enableVersioning: true
handle: calendarPrices
name: 'Rooster en tarieven'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  521def3a-78c9-4e7b-8cb5-40b18c2c0705:
    enabledByDefault: true
    hasUrls: true
    template: calendar-prices/entry
    uriFormat: rooster-en-tarieven
type: single
