enableVersioning: true
handle: newsOverview
name: 'Nieuws - Overzicht'
propagationMethod: all
siteSettings:
  521def3a-78c9-4e7b-8cb5-40b18c2c0705: # Biljoenbad
    enabledByDefault: true
    hasUrls: true
    template: news/overview.twig
    uriFormat: nieuws
type: single
