enableVersioning: true
handle: team
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  521def3a-78c9-4e7b-8cb5-40b18c2c0705: # Biljoenbad
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
