# This is a basic workflow to help you get started with Actions
name: Deploy Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#      # Cache
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Cache Node Modules
        id: yarn-cache
        uses: actions/cache@v2
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node Modules
        run: yarn

      - name: Install Composer Dependencies
        run: composer install

      - name: Build Project
        run: gulp build

      - name: Setup Staging Environment
        run: |
          echo "SSH_HOST=${{ secrets.STAGING_REMOTE_USER }}@${{ secrets.STAGING_HOST }}" >> $GITHUB_ENV
          echo "SSH_OPTS=-i ~/.ssh/deploy_key" >> $GITHUB_ENV
          echo "DEPLOY_DIR=${{ secrets.STAGING_ROOT }}" >> $GITHUB_ENV
          echo "CRAFT_ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.STAGING_DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.STAGING_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_DATABASE=${{ secrets.STAGING_DB_NAME }}" >> $GITHUB_ENV
          echo "DB_PORT=3306" >> $GITHUB_ENV
          echo "DB_SERVER=${{ secrets.STAGING_DB_SERVER }}" >> $GITHUB_ENV
          echo "SITEURL=${{ secrets.STAGING_URL }}" >> $GITHUB_ENV
          echo "SECURITY_KEY=${{ secrets.SECURITY_KEY }}" >> $GITHUB_ENV

      - name: Deploy to Staging
        run: |
          echo $SSH_HOST >> debug
          chmod u+x deploy-staging.sh
          ./deploy-staging.sh

      - name: Checkout Private Critical CSS Action Repo
        uses: actions/checkout@v2
        with:
          repository: Appmanschap/Critical-CSS
          path: .github/actions/critical-css

      - name: Generate Critical CSS
        uses: ./.github/actions/critical-css
        with:
          serverBaseUrl: ${{ secrets.STAGING_URL }}
          destinationPath: './criticalcss/'
          configPath: './critical-conf.json'
          sync: 'true'
          sshPrivateKeyPath: '~/.ssh/antagonist-ssh'
          sshHost: ${{ secrets.STAGING_REMOTE_USER }}@${{ secrets.STAGING_HOST }}
          targetDir: './${DEPLOY_DIR}/public_html/assets/criticalcss/'
